### ISSUE TITLE
Issue with city neighbors.

### ISSUE THREAD

**Issue by Shadownite64** [klyte45/AddressesMod#28]
I've noticed after the recent update that the feature to add neighbors in-game went away, I'm pretty sure this wasn't intentional.
![image](https://user-images.githubusercontent.com/68400080/137821013-00336339-b4eb-4528-b7ec-c03a998ce995.png)

**Comment by klyte45** [comment]
Please take a look in the complete mod version. It must be solved at version 3.1.0r1, released Sunday.
You can check it at this mod menu in options window

**Comment by Shadownite64** [comment]
Ah I see, my version is still 3.1.0r0 for some reason, Ill re-subscribe to it and see.
