### ISSUE TITLE
Numbered roads

### ISSUE THREAD

**Issue by Skippern** [klyte45/AddressesMod#3]
There should be a syntax in RoadPrefix for numbered roads (BR-060, E-6, N-3, A1, etc.) I would like the ability to have such numbers on highways, i.e. with ```Ghw(2,)=N-{#} {0} Highway {7} ({5}-{6})``` where ```{#}``` represents a random number.

**Comment by klyte45** [comment]
I was thinking how to do it in a smart way (because there's no intelligence to know if a pair of one-way roads are the same but with different directions), but I will add this simplest one mode in the next version. I alert it will work well only for two-way segments - the separated one-way pairs will probably get different numbers for each track.

**Comment by Skippern** [comment]
Pair of oneway roads are already named separately, finding an intelligent way to pair them would change a lot in the game.

**Comment by klyte45** [comment]
Actually, Addresses already generate the pair of roads with same name, if both starts and ends at same district/border city, like in this example:
![image](https://user-images.githubusercontent.com/11671356/62834792-8e615280-bc27-11e9-9beb-c819559de025.png)

They also share almost the same mileage counter to generate the exit name. The configuration at qualifier file the to generate this pattern is:
`hw(2,)=Rod. {5}-{6} {7}`
*One-way **w** Higways **h** of two or more lanes **(2,)** will be named as "Rod. " + Starting district/city **{5}** + Ending district/city **{6}** + road direction **{7}** *

In this image, the road O means West and the L means East (it's in portuguese), but it changes along the current selected locale. This always use as reference that the district/city at North or West is the start district, so it generate the same name for both.

**Comment by Skippern** [comment]
I am familiar with the Portuguese language, having myself lived several years in Brazil.

I have been looking for the behaviour of pairing road names, but havn't observed this behaviour yet. It might be that some features in the mod is not working on Mac, as I have noticed several mods looking different on my Mac than I observe from streamers playing on Windows 7/8/10 systems.

**Comment by klyte45** [comment]
Well, that's a problem that I can't confirm or deny... I can't see a cause for a different behavior of this feature at Mac, but I don't know so much about the differences of this game between the platforms.
Just try to add this configuration I told in the qualifier file (if there's no line like that) and then create a simple road that starts in a district and ends in another (can be just 3 or 4 segments length each direction) and look what happens.

**Comment by Skippern** [comment]
When looking at your syntax, it might be that you don't use the name tag {0}, therefor not having random naming. I also have multiple variations (National Highway, Regional Highway, Interstate, etc.) and have Northbound and Southbound with completely different naming

**Comment by klyte45** [comment]
I see... Yes, I avoid the random names in this layout once it doesn't generate the same name in this case.
Maybe you can do a trick: once the name is created by the name seed configured in segment, Try put all the road with the same name by dragging the green node of name by all them long and then destroying the road that you linked the both ways. This may generate the same name for both after doing this.

**Comment by klyte45** [comment]
Well, I guess I will solve your problem in a near future with a patch that allow to copy-and-paste road seeds. It will allow to roads their name linked by using the same random seed used to generate the name.
