### ISSUE TITLE
Problem with Last names

### ISSUE THREAD

**Issue by Shadownite64** [klyte45/AddressesMod#30]
Whenever I set the last name file, no citizen is given a first name, only a last name.
![image](https://user-images.githubusercontent.com/68400080/138602174-90257947-b6ea-40ca-ac3d-7e308443c003.png)

**Comment by klyte45** [comment]
Probably you missed the first name placeholder at the last names file. Look this example file to see how the file should look like:
https://github.com/klyte45/AddressesFiles/blob/master/pt-br/CitizenLastName/Br.txt

The {0} will be replaced by the first/given name in game. This design was done this way to support eastern people names, that the given name is actually the last name (and them the {0} will be added after the surname in the file for these situations)
