### ISSUE TITLE
Conflict with More CitizenUnits mod (I think)

### ISSUE THREAD

**Issue by gitblogger** [klyte45/AddressesMod#32]
There seems to be an issue (see title) that stops buses from spawning. I advised the creator of the other mod and he says it's to do with this mod.

Here is my output log: https://1drv.ms/t/s!AjCgUJmK-Yl5grgs9J5W5cP0WWAHSA

**Comment by gitblogger** [comment]
Hello?

**Comment by klyte45** [comment]
No way this mod to be related. This mod doesn't deals with Citizen Units.
Plus, I found no mention to issues for this mod in log (except the controller access warnings, that are harmless)
