### ISSUE TITLE
How to rename neighbors randomly

### ISSUE THREAD

**Issue by HitchenTGuan** [klyte45/AddressesMod#37]
Hi , Appreciate for you mod
   I am looking for a mod that can change my neighbors name but i found I only can change name by degree
   I want my city connect to the city all over the world but if add name by degree I have to create the connection every degree and that cause overdose of vehicle in my city 
So any help
Thank for your work

**Comment by klyte45** [comment]
Well, you don't need to create a neighbor to every degree, just create degree ranges.

Ex: Setting to start in 0 as City A and 180 as City B, City A will be reached from 0 to 179 and City B from 180 to 359.
